### ISSUE TITLE
Where should this plugin be installed?

### ISSUE THREAD

**Issue by sangwinc** [marcusgreen/moodle-tool_stackui#1]
Stupid question, but where should this be installed?  I tried /local but that failed!

**Comment by marcusgreen** [comment]
It goes under yourmoodle /admin/tool
Frankenstyle doesn't include the admin bit so the name can be misleading.
You need to create the cohort for it to work....

**Comment by marcusgreen** [comment]
So it ends up as /admin/tool/stackui
